exclusion de fichiers dans la configuration de psalm et phpstan
assurance-maladie-digital/qualytou pull request #10
Opened 2022-03-25 14:57 UTC by jpmerlin

2022-03-25 15:00 UTC, roukmoute requested changes

2022-03-25 17:16 UTC, jpmerlin commented on psalm.xml
> +            <file name="public/index.php" />
en fait j'ai un erreur au avec `grumphp pre:commit` mais pas avec `grumphp run`

2022-03-28 11:42 UTC, roukmoute commented on psalm.xml
> +            <file name="public/index.php" />
Ok au vu de ce qui a été dit [ici](https://github.com/vimeo/psalm/discussions/7823#discussion-3968361), on va merger cette P.R.

2022-03-28 11:42 UTC, roukmoute approved these changes

2022-03-28 11:44 UTC, merged